const actions = {
  EAT: "EAT",
  MOVE: "MOVE",
  CHANGE_DIRECTION: "CHANGE_DIRECTION",
  RESET_GAME: "RESET_GAME",
  START_GAME: "START_GAME",
  STOP_GAME: "STOP_GAME",
  UPDATE_SCORE: "UPDATE_SCORE",
  UPDATE_HIGH_SCORE: "UPDATE_HIGH_SCORE",
  CHECK_COLLISION: "CHECK_COLLISION",
};
